
twig:
    default_path: '%kernel.project_dir%/templates'
    path: '%kernel.project_dir%/vendor/knplabs/knp-paginator-bundle/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
   