<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerITZJQx8\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerITZJQx8/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerITZJQx8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerITZJQx8\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerITZJQx8\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ITZJQx8',
    'container.build_id' => '07d29e45',
    'container.build_time' => 1646132918,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerITZJQx8');
