<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXgexiwG\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXgexiwG/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXgexiwG.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXgexiwG\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXgexiwG\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XgexiwG',
    'container.build_id' => '346a0fac',
    'container.build_time' => 1646127267,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXgexiwG');
