<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO1F40Ic\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO1F40Ic/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO1F40Ic.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO1F40Ic\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerO1F40Ic\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'O1F40Ic',
    'container.build_id' => '6fbbb802',
    'container.build_time' => 1645298365,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO1F40Ic');
